# Generated by Django 5.2.7 on 2025-11-06 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["email"],
                "permissions": [("can_block_users", "Может блокировать пользователей")],
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_blocked",
        ),
    ]
