# Generated by Django 5.2.7 on 2025-11-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_client_comment_alter_client_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="comment",
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name="Комментарий"),
        ),
    ]
