# Generated by Django 5.2.7 on 2025-11-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_client_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["owner"],
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
    ]
