# Generated by Django 5.2.7 on 2025-11-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country", models.CharField(max_length=20, verbose_name="Страна")),
                ("address", models.CharField(max_length=150, verbose_name="Юридический адрес")),
                ("email", models.EmailField(max_length=50, verbose_name="Адрес электронной почты")),
            ],
            options={
                "verbose_name": "контакты",
                "verbose_name_plural": "контакты",
                "ordering": ["country", "address"],
            },
        ),
        migrations.CreateModel(
            name="MessageFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Имя пользователя")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail пользователя")),
                ("message", models.TextField(max_length=2000, verbose_name="Сообщение пользователя")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "обратная связь",
                "verbose_name_plural": "обратная связь",
                "ordering": ["name", "email", "created_at"],
            },
        ),
    ]
