# Generated by Django 5.2.7 on 2025-11-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={
                "ordering": ["created_at"],
                "permissions": [("can_disable_campaigns", "Может отключать рассылки")],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Создана"),
                    ("RUNNING", "Запущена"),
                    ("FINISHED", "Завершена"),
                    ("DISABLED", "Отключена"),
                ],
                default="CREATED",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
